### ISSUE TITLE
Cleanup for Guide + SDK repositories

### ISSUE THREAD

**Issue by IshanDaga** [golain-io/golain-esp-sdk#14]
### Tasks
- [ ] Cleanup Shell application, add in-code comments and a guide
- [x] nanopb submodule commit is wrong - cmake error because of this
- [x] generated `.c` files have the wrong include paths for generated `.h` files from nanopb
